### PR TITLE
Remove "add linter" skill checkbox

### PR DESCRIPTION
**Pull request by flyrightsister**
This skill isn't covered in this module.

### CODE REVIEW

**Comment by deadlyicon** [comment]
I want it to be! Instead of removing this can we find some resources for Atom and Sublime Text 3 to install linters into your editor?

**Comment by justinhaaheim** [comment]
Definitely support this. I just sent a blurb out to phase-3 about setting up linting, now copied here: https://github.com/justinhaaheim/Coding-Resources/blob/master/JS_STYLE.md

I can put it on my todo list to write something up for the curriculum, or we can just link to the page above. What do you think @deadlyicon ?

**Comment by deadlyicon** [comment]
@justinhaaheim please add that link to any modules it might be helpful for. Also feel free to add an exercise to the `Installfest` module walking folks through the install of a linter

**Comment by flyrightsister** [comment]
Hi, @justinhaaheim @deadlyicon  -- Please note that I submitted a pull request for installapalooza for this: 

https://github.com/GuildCrafts/Installapalooza/pull/1

**Comment by deadlyicon** [comment]
merged!

**Pull request closed without merging**
