### PR TITLE
Minor changes to 321 Contacts Template

### PR DESCRIPTION
**Pull request by EthanJStark**
renamed variable for clarity

### CODE REVIEW

**Comment by EthanJStark** [comment]
Also: `must be sorted by first and last name` is ambiguous.

**Comment by deadlyicon** [comment]
its technically not ambiguous to say "sorted by X and Y" but I it could be more clear here that we mean full name.

**Comment by jrpool** [comment]
I'd say "sorted by X and Y" could mean "sorted by X, then Y" or "sorted by Y, then X". If it really means "sorted by X Y", then the "and" formulation invites miscommunication.

**Comment by deadlyicon** [comment]
touché @jrpool

**Comment by jrpool** [comment]
@deadlyicon’s version of the gold star decal. Seems to be an effective motivator.

**Pull request merged**
